BaseURL: "http://romtin.github.io"
LanguageCode: "ja-jp"
Title: "後ろを向いて後退します.com"

Params:
    Author: "Michael"
    DateForm: "Mon, Jan 2, 2006"
    GoogleAnalyticsUserID: ""
    GravatarHash: ""
    Disqus: ""
    SyntaxHighlightTheme: "solarized_dark.min.css"
    ShowRelatedPost: True
    ShowTagCloud: True
    # profile
    UserName: "Michael"
    Profpic: "momiji"
    Birth: "Fri, Aug 18, 1995"
    Facebook: "pres.romtin"
    Twitter: "mic_psm"
    Github: "RomTin"
    Description: "寒いところにある大学に通っています。\n恒常的に金欠。"
    Interests: "debian, windows, vim, web, CTF(baby), 競プロ, Scala, Haskell, Elixir, Python, Go, D, C++"
    Others: "英語(English), 音楽, 麻雀, 車, バイク, 東方, ストライクウィッチーズ, アイドルマスター, ガールズ&パンツァー"

Indexes:
    tag: "tags"

permalinks:
    post: /blog/:year/:month/:day/:title/

MetadataFormat: "yaml"

